### ISSUE TITLE
404 when trying to access proxy_url in `get_label_values`

### ISSUE THREAD

**Issue by iameminmammadov** [jupyterhub/grafana-dashboards#98]
### Bug description

404 Error appears in `get_label_values` and seems to be linked to `proxy_url`. 

### Your personal set up

Running Jupyterhub on K8s on GKE. Prometheus and Grafana were installed via helm: `prometheus-community/kube-prometheus-stack`

**Comment by JohanRuuskanen** [comment]
I ran into the same issue with the `kube-prometheus-stack` helm chart, but managed to fix it with a dirty hack in `./deploy.py`. 

For me the problem was that the helm chart adds mulitple datasources to `Grafana`, and `./deploy.py` tries to select prometheus simply with `prom_id = datasources[0]["id"]`.

**Comment by iameminmammadov** [comment]
Forgot to update. I fixed the problem with using the new version for Grafana API. The code is for previous version and doesn't work with the latest one.
